Repository CD-Sofias/MojRozvrh-FE, pull requests merged in 2024-04, with the labels that each got.

#14 features/groups-&-schedule_connection
  src/app/app.component.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.module.ts
  src/app/dashboard/groups/groups.component.css
  src/app/dashboard/groups/groups.component.html
  src/app/dashboard/groups/groups.component.ts
  src/app/dashboard/schedule/myschedule.component.css
  src/app/dashboard/schedule/myschedule.component.html
  src/app/dashboard/schedule/myschedule.component.ts
  src/data.ts
Labels: enhancement

#15 feature/types
  src/app/types/address.ts
  src/app/types/classroom.ts
  src/app/types/department.ts
  src/app/types/faculty.ts
  src/app/types/group.ts
  src/app/types/schedule.ts
  src/app/types/scheduleCell.ts
  src/app/types/subject.ts
  src/app/types/teacher.ts
  src/app/types/user.ts
Labels: enhancement

#16 feature/services
  src/app/auth/auth.service.ts
  src/app/services/classroom.service.ts
  src/app/services/department.service.ts
  src/app/services/faculty.service.ts
  src/app/services/group.service.ts
  src/app/services/schedule.service.ts
  src/app/services/subject.service.ts
  src/app/services/teacher.service.ts
  src/app/services/user.service.ts
Labels: enhancement

#18 feature/auth-interceptor
  src/app/app.config.ts
  src/app/auth.interceptor.ts
Labels: enhancement

#19 Using service in groups, fix paths in services
  src/app/dashboard/groups/groups.component.html
  src/app/dashboard/groups/groups.component.ts
  src/app/services/schedule.service.ts
  src/app/services/user.service.ts
Labels: bug, enhancement

#20 Adding logout, added username writing in the header
  src/app/auth/auth.service.ts
  src/app/dashboard/header/header.component.html
  src/app/dashboard/header/header.component.ts
  src/app/services/user.service.ts
Labels: enhancement

#21 bugfix/fix-auth-redirect
  src/app/auth.interceptor.ts
Labels: bug

#22 bugfix/fix_schedule_cell
  src/app/dashboard/dashboard-routing.module.ts
  src/app/dashboard/dashboard.module.ts
  src/app/dashboard/groups/groups.component.ts
  src/app/dashboard/schedule/myschedule.component.html
  src/app/dashboard/schedule/myschedule.component.ts
  src/app/services/schedule-cell.service.ts
  src/app/types/scheduleCell.ts
  src/styles.css
Labels: enhancement

#23 bugfix/schedule_cell_search
  src/app/dashboard/schedule/myschedule.component.html
  src/app/dashboard/schedule/myschedule.component.ts
Labels: bug

#24 Feature/fix
  src/app/app.routes.ts
  src/app/auth/auth.guard.ts
  src/app/auth/auth.service.ts
Labels: bug, enhancement

#25 features/schedule-table-creator
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/auth.interceptor.ts
  src/app/dashboard/admin/schedule-table-creator/department/department.component.html
  src/app/dashboard/admin/schedule-table-creator/department/department.component.ts
  src/app/dashboard/admin/schedule-table-creator/faculty/faculty.component.html
  src/app/dashboard/admin/schedule-table-creator/faculty/faculty.component.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator-routing.module.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.css
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.html
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.module.ts
  src/app/dashboard/admin/schedule-table-creator/teacher/teacher.component.html
  src/app/dashboard/admin/schedule-table-creator/teacher/teacher.component.ts
  src/app/dashboard/dashboard-routing.module.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.module.ts
  src/app/dashboard/schedule/myschedule.component.html
  src/app/services/department.service.ts
  src/app/services/teacher.service.ts
  src/styles.css
Labels: enhancement

#26 feature/dashboard
  src/app/app.routes.ts
  src/app/dashboard/admin/schedule-table-creator/addresses/addresses.component.html
  src/app/dashboard/admin/schedule-table-creator/addresses/addresses.component.ts
  src/app/dashboard/admin/schedule-table-creator/classrooms/classrooms.component.html
  src/app/dashboard/admin/schedule-table-creator/classrooms/classrooms.component.ts
  src/app/dashboard/admin/schedule-table-creator/department/department.component.html
  src/app/dashboard/admin/schedule-table-creator/department/department.component.ts
  src/app/dashboard/admin/schedule-table-creator/faculty/faculty.component.html
  src/app/dashboard/admin/schedule-table-creator/faculty/faculty.component.ts
  src/app/dashboard/admin/schedule-table-creator/groups/groups.component.html
  src/app/dashboard/admin/schedule-table-creator/groups/groups.component.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator-routing.module.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.css
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.html
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.component.ts
  src/app/dashboard/admin/schedule-table-creator/schedule-table-creator.module.ts
  src/app/dashboard/admin/schedule-table-creator/subjects/subjects.component.html
  src/app/dashboard/admin/schedule-table-creator/subjects/subjects.component.ts
  src/app/dashboard/admin/schedule-table-creator/teacher/teacher.component.html
  src/app/dashboard/admin/schedule-table-creator/teacher/teacher.component.ts
  src/app/dashboard/dashboard-routing.module.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.module.ts
  src/app/dashboard/header/header.component.css
  src/app/dashboard/header/header.component.ts
  src/app/dashboard/schedule/myschedule.component.ts
  src/app/services/address.service.ts
  src/app/services/classroom.service.ts
  src/app/services/department.service.ts
  src/app/services/group.service.ts
  src/app/services/subject.service.ts
  src/app/services/teacher.service.ts
  src/app/types/classroom.ts
  src/app/types/department.ts
  src/app/types/group.ts
  src/app/types/teacher.ts
  src/index.html
  src/styles.css
Labels: enhancement
